version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: usrlshorteneruser
      MYSQL_PASSWORD: anothersecurepassword

  urlshortener:
    depends_on:
      - db
    image: urlshortener:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      URL_SHORTENER_DB_USER: usrlshorteneruser
      URL_SHORTENER_DB_PASSWORD: anothersecurepassword